### ISSUE TITLE
GLOOMROT UPDATE COMPATIBLITY?

### ISSUE THREAD

**Issue by leomaniaplayz** [PureDark/VRisingDLSSMod#7]
Does this work with the latest gloomrot update? 

Also when you say install like any other mod can you be more specific, because certain mods install differently and in different folders, so do you mean just put the .DLLs files into the bepinex plugins folder on the client side?

**Comment by RoseIlanga** [comment]
As far as I know, it should just go in the BepInEx/plugins directory, yeah. And the current release doesn't work with Gloomrot, but I've compiled the latest version with the Gloomrot updates from the repository myself. Haven't tested it yet, though.

**Comment by PweSol** [comment]
> As far as I know, it should just go in the BepInEx/plugins directory, yeah. And the current release doesn't work with Gloomrot, but I've compiled the latest version with the Gloomrot updates from the repository myself. Haven't tested it yet, though.

Could you then perhaps share the compiled build please?

**Comment by PweSol** [comment]
> As far as I know, it should just go in the BepInEx/plugins directory, yeah. And the current release doesn't work with Gloomrot, but I've compiled the latest version with the Gloomrot updates from the repository myself. Haven't tested it yet, though.

I compiled it with your changes and it works to an extend. DLSS seems to works, FSR2 definitely works, XeSS doesn't work and crashes to desktop. This is the log for it that I get:
```Process terminated. A callback was made on a garbage collected delegate of type 'PerfMod!PureDark.VRising.PerfMod.Upscale.UpscaleFlat+LogDelegate::Invoke'.
Repeat 2 times:
--------------------------------
   at PureDark.VRising.PerfMod.Upscale.UpscaleFlat.SimpleInit(Int32, PureDark.VRising.PerfMod.Upscale.UpscaleMethod, PureDark.VRising.PerfMod.Upscale.UpscaleProfile, Int32, Int32, Boolean, Boolean, Boolean, Boolean, Boolean, Boolean, PureDark.VRising.PerfMod.Upscale.DXGI_FORMAT)
--------------------------------
   at PureDark.VRising.PerfMod.Upscale.UpscaleFlat.Setup()
   at PureDark.VRising.PerfMod.Upscale.UpscaleFlat+<DelayEnableUpscale>d__36.MoveNext()
   at PureDark.VRising.PerfMod.MISC.MelonCoroutines.ProcessNextOfCoroutine(System.Collections.IEnumerator)
   at PureDark.VRising.PerfMod.MISC.MelonCoroutines.Process()
   at PureDark.VRising.PerfMod.MISC.MelonCoroutineCallbacks.Update()
   at DynamicClass.Trampoline_VoidThisPureDark.VRising.PerfMod.MISC.MelonCoroutineCallbacksUpdate(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*)
   at DynamicClass.Invoker_VoidThis(IntPtr, Il2CppInterop.Runtime.Runtime.Il2CppMethodInfo*, IntPtr, IntPtr*)
```
The mod loads fine at startup it seems but I also get this error in BepInEx:
```
[Error  :   BepInEx] Error loading [VRisingPerformanceMod 1.1.0]: System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at PureDark.VRising.PerfMod.PerformancePlugin.LoadAllDlls()
   at PureDark.VRising.PerfMod.PerformancePlugin.Init()
   at PureDark.VRising.PerfMod.PerformancePlugin.Load()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 134
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
```

**Comment by PweSol** [comment]
So it turns out the latest official mod release is missing igxess.dll which is supposed to be required for the included XeSS 1.1 version to work. However adding the appropriate dll version doesn't fix the crash. What does work though is updating XeSS straight to its latest 1.2 version. 

If anyone wants to try the mod with the changes made by the awesome people here, you can get it [here](https://github.com/PweSol/VRisingPerfMod/releases/download/v1.1.0-GLOOMROT/PureDark-VRisingPerfMod-1.1.0-GLOOMROT.zip).

**Comment by sevawk** [comment]
> So it turns out the latest official mod release is missing igxess.dll which is supposed to be required for the included XeSS 1.1 version to work. However adding the appropriate dll version doesn't fix the crash. What does work though is updating XeSS straight to its latest 1.2 version.
> 
> If anyone wants to try the mod with the changes made by the awesome people here, you can get it [here](https://github.com/PweSol/VRisingPerfMod/releases/download/v1.1.0-GLOOMROT/PureDark-VRisingPerfMod-1.1.0-GLOOMROT.zip).


I have been looking for months for this and I'm so glad there's kind people like you all that have updated the mod! Thank you so much! WOOT! 
For those of you who want to add this mod manually to Thunderstore mod manager, go into settings and scroll down and you'll see an ADD LOCAL MOD option. Enjoy! God bless you all!

**Comment by sevawk** [comment]
I will leave you guys with this, adding the mod caused some invisible environment items to grow into my house, some visible like dry brush, thru my flooring, even reaching the second floor. Causing me to be blocked by some invisible wall I have to walk around and trying to move furniture into that area says "blocked by environment"
